import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { buildPalette, customBase, type CustomChoice } from '../lib/palette';

export type ThemeId =
  | 'hud' | 'modernist' | 'midnight' | 'paper' | 'contrast'
  | 'water' | 'grass' | 'psychic' | 'electric' | 'fire' | 'steel' | 'ice'
  | 'custom';
export type MotionPref = 'on' | 'off';

/**
 * The ids are historical and deliberately unchanged.
 *
 * `hud` and `modernist` name a look; the labels now name what people actually
 * pick by, which is dark or light. Renaming the ids would break every
 * `[data-theme='hud']` selector across four stylesheets and silently reset the
 * saved preference of anyone who already has one, for a cosmetic gain.
 */
export const THEMES: { id: ThemeId; label: string; blurb: string; scheme: 'dark' | 'light' }[] = [
  { id: 'hud', label: 'Dark', blurb: 'Tactical readout — the original', scheme: 'dark' },
  { id: 'midnight', label: 'Midnight', blurb: 'Deep indigo, softer contrast', scheme: 'dark' },
  { id: 'modernist', label: 'Light', blurb: 'Swiss editorial', scheme: 'light' },
  { id: 'paper', label: 'Paper', blurb: 'Warm ivory, low glare', scheme: 'light' },
  { id: 'contrast', label: 'Contrast', blurb: 'Maximum separation, no chrome', scheme: 'dark' },
  // Type themes, generated by scripts/build-themes.mjs. Every pairing the UI
  // renders is contrast-checked there, so adding one here without adding it
  // to the generator would ship a theme with no palette at all — which
  // token-parity now catches.
  { id: 'water', label: 'Water', blurb: 'Deep ocean, cyan signal', scheme: 'dark' },
  { id: 'grass', label: 'Grass', blurb: 'Canopy green, citrus signal', scheme: 'dark' },
  { id: 'psychic', label: 'Psychic', blurb: 'Plum dusk, magenta signal', scheme: 'dark' },
  { id: 'electric', label: 'Electric', blurb: 'Charcoal, high-voltage signal', scheme: 'dark' },
  { id: 'fire', label: 'Fire', blurb: 'Forge dark, ember signal', scheme: 'dark' },
  { id: 'steel', label: 'Steel', blurb: 'Brushed metal, cool ink', scheme: 'light' },
  { id: 'ice', label: 'Ice', blurb: 'Glacier white, frost signal', scheme: 'light' },
];

/**
 * The user's own theme, kept apart from THEMES.
 *
 * It has no stylesheet block — its tokens are written into a style element at
 * runtime from the choice below — so listing it alongside the baked themes
 * would break the guard that every listed theme has a palette.
 */
export const CUSTOM_THEME = { id: 'custom' as ThemeId, label: 'Yours', blurb: 'Build your own palette' };

const THEME_IDS = THEMES.map((t) => t.id);

const THEME_KEY = 'paragon.theme';
const CUSTOM_KEY = 'paragon.theme.custom';
const MOTION_KEY = 'paragon.motion';

/** Read the persisted choice, falling back to the OS preference. */
function initialTheme(): ThemeId {
  if (typeof window === 'undefined') return 'hud';
  const saved = window.localStorage.getItem(THEME_KEY);
  // 'custom' is valid but is not in THEME_IDS — it has no stylesheet block.
  if (saved === 'custom' && initialCustom()) return 'custom';
  if (saved && (THEME_IDS as string[]).includes(saved)) return saved as ThemeId;
  return window.matchMedia?.('(prefers-color-scheme: light)').matches ? 'modernist' : 'hud';
}

function initialCustom(): CustomChoice | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = window.localStorage.getItem(CUSTOM_KEY);
    if (!raw) return null;
    const v = JSON.parse(raw) as CustomChoice;
    return v && v.bg && v.accent && v.accent2 ? v : null;
  } catch {
    return null;
  }
}

function initialMotion(): MotionPref {
  if (typeof window === 'undefined') return 'on';
  const saved = window.localStorage.getItem(MOTION_KEY);
  if (saved === 'on' || saved === 'off') return saved;
  return window.matchMedia?.('(prefers-reduced-motion: reduce)').matches ? 'off' : 'on';
}

interface ThemeContextValue {
  theme: ThemeId;
  setTheme: (t: ThemeId) => void;
  /** The user's own palette, or null until they build one. */
  custom: CustomChoice | null;
  setCustom: (c: CustomChoice) => void;
  toggleTheme: () => void;
  motion: MotionPref;
  setMotion: (m: MotionPref) => void;
  toggleMotion: () => void;
  /** True when animation should be suppressed — drives JS-side effects that
   *  CSS alone can't reach (e.g. the R3F camera auto-orbit). */
  reduced: boolean;
}

const ThemeContext = createContext<ThemeContextValue | null>(null);

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<ThemeId>(initialTheme);
  const [custom, setCustomState] = useState<CustomChoice | null>(initialCustom);
  const [motion, setMotionState] = useState<MotionPref>(initialMotion);

  /**
   * The custom palette is written into a style element rather than a
   * stylesheet, because it does not exist until someone builds it. Same
   * `buildPalette` the shipped themes are baked with, so a palette that would
   * fail the build fails here too.
   */
  useEffect(() => {
    const ID = 'paragon-custom-theme';
    let el = document.getElementById(ID) as HTMLStyleElement | null;
    if (!custom) {
      el?.remove();
      return;
    }
    if (!el) {
      el = document.createElement('style');
      el.id = ID;
      document.head.appendChild(el);
    }
    const { tokens } = buildPalette(customBase(custom));
    const body = Object.entries(tokens).map(([k, v]) => `  ${k}: ${v};`).join('\n');
    el.textContent = `:root[data-theme='custom'],\n.theme-swatch-face[data-theme='custom'] {\n${body}\n}`;
    window.localStorage.setItem(CUSTOM_KEY, JSON.stringify(custom));
  }, [custom]);

  // Both preferences live as attributes on <html> so CSS can key off them
  // without any component knowing the current theme.
  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme);
    window.localStorage.setItem(THEME_KEY, theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.setAttribute('data-motion', motion);
    window.localStorage.setItem(MOTION_KEY, motion);
  }, [motion]);

  const setTheme = useCallback((t: ThemeId) => setThemeState(t), []);
  const setCustom = useCallback((c: CustomChoice) => setCustomState(c), []);
  const setMotion = useCallback((m: MotionPref) => setMotionState(m), []);
  // Cycles through the list rather than flipping a pair, now that there are
  // more than two. The keyboard shortcut and any caller that just wants "the
  // next one" keeps working without knowing how many exist.
  const toggleTheme = useCallback(
    () => setThemeState((t) => THEME_IDS[(THEME_IDS.indexOf(t) + 1) % THEME_IDS.length]),
    [],
  );
  const toggleMotion = useCallback(() => setMotionState((m) => (m === 'on' ? 'off' : 'on')), []);

  const value = useMemo<ThemeContextValue>(
    () => ({ theme, setTheme, custom, setCustom, toggleTheme, motion, setMotion, toggleMotion, reduced: motion === 'off' }),
    [theme, setTheme, custom, setCustom, toggleTheme, motion, setMotion, toggleMotion],
  );

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
}

export function useTheme(): ThemeContextValue {
  const ctx = useContext(ThemeContext);
  if (!ctx) throw new Error('useTheme must be used within ThemeProvider');
  return ctx;
}
