import speciesRaw from '../data/species.json';
import opponentsRaw from '../data/opponents.json';
import type { ChargeMove, FastMove, League, LeagueId, Species, SpeciesRef } from './types';
import { artefact } from './artefact';

/**
 * The roster is now the whole released game — every species and alternate
 * form (~1123 entries), generated by scripts/build-data.mjs from PvPoke's
 * game master. There is no longer a separate "curated roster" vs "broad
 * opponent pool" split: everything is selectable, and league membership is
 * expressed per-species via `leagues` / `leagueRank`.
 *
 * Shadows are not separate rows. A Shadow shares its base form's stats,
 * typing and movepool exactly, so it's modelled as a flag on the selection
 * (SpeciesRef) rather than a duplicate entry. See SHADOW_ATK_MULT in engine.ts.
 */
/**
 * species.json interns its move objects: the same BODY_SLAM appeared in every
 * species that learns it — 7730 embedded objects across the roster, but only
 * 567 distinct ones, which was 62% of the file. Species now hold keys into a
 * `moves` table.
 *
 * Rehydrating here, once at module load, means the in-memory shape is exactly
 * what it always was and no consumer knows the difference. Shared references
 * are a bonus: identity comparison on moves now works.
 */
interface RawSpecies
  extends Omit<Species, 'fastMoves' | 'chargeMoves' | 'chargeMove' | 'chargeMove2' | 'leagueMoves'> {
  fastMoves: string[];
  chargeMoves: string[];
  chargeMove: string;
  chargeMove2: string | null;
  leagueMoves?: Partial<Record<LeagueId, { fast: string; charge: string; charge2: string | null }>>;
}
const raw = artefact<{
  moves: Record<string, FastMove & ChargeMove>;
  species: RawSpecies[];
}>(speciesRaw, 'species.json', ['moves', 'species'], 'npm run data');

export const SPECIES: Species[] = raw.species.map((s) => ({
  ...s,
  fastMoves: s.fastMoves.map((k) => raw.moves[k] as FastMove),
  chargeMoves: s.chargeMoves.map((k) => raw.moves[k] as ChargeMove),
  chargeMove: raw.moves[s.chargeMove] as ChargeMove,
  chargeMove2: s.chargeMove2 ? (raw.moves[s.chargeMove2] as ChargeMove) : null,
  leagueMoves: s.leagueMoves
    ? Object.fromEntries(
        Object.entries(s.leagueMoves).map(([lg, m]) => [
          lg,
          {
            fast: raw.moves[m.fast] as FastMove,
            charge: raw.moves[m.charge] as ChargeMove,
            charge2: m.charge2 ? (raw.moves[m.charge2] as ChargeMove) : null,
          },
        ]),
      )
    : undefined,
}));

/**
 * The loadout a species actually runs in a given league.
 *
 * Falls back to the default pair, which is what every species without a
 * league-specific entry uses. Everything that simulates a mon as an *opponent*
 * should resolve through here: using one league's recommended set in another
 * is the difference between Registeel's Great and Ultra builds.
 */
export function movesFor(
  species: Species,
  league: LeagueId,
): { fast: FastMove; charges: ChargeMove[] } {
  const m = species.leagueMoves?.[league];
  const fast = m?.fast ?? species.fastMoves[0];
  const c1 = m?.charge ?? species.chargeMove;
  const c2 = m ? m.charge2 : species.chargeMove2;
  return { fast, charges: c2 ? [c1, c2] : [c1] };
}

export const SPECIES_BY_ID: Map<string, Species> = new Map(SPECIES.map((s) => [s.id, s]));

/** Retained name: the pool and the roster are now the same thing. */
export const OPPONENT_POOL_BY_ID = SPECIES_BY_ID;

export const OPPONENTS: Record<LeagueId, string[]> = opponentsRaw as Record<LeagueId, string[]>;

export const LEAGUES: League[] = [
  { id: 'great', label: 'Great 1500', name: 'Great League · 1500', cap: 1500, uncapped: false },
  { id: 'ultra', label: 'Ultra 2500', name: 'Ultra League · 2500', cap: 2500, uncapped: false },
  { id: 'master', label: 'Master', name: 'Master League · no cap', cap: 1e9, uncapped: true },
];

export const LEAGUE_BY_ID: Map<LeagueId, League> = new Map(LEAGUES.map((l) => [l.id, l]));

const SHADOW_SUFFIX = '_shadow';

/** `machamp_shadow` → `{ id: 'machamp', shadow: true }` */
export function parseRef(ref: string): SpeciesRef {
  return ref.endsWith(SHADOW_SUFFIX)
    ? { id: ref.slice(0, -SHADOW_SUFFIX.length), shadow: true }
    : { id: ref, shadow: false };
}

/** `{ id: 'machamp', shadow: true }` → `machamp_shadow` */
export function makeRef(id: string, shadow: boolean): string {
  return shadow ? `${id}${SHADOW_SUFFIX}` : id;
}

export function speciesOf(ref: string): Species | undefined {
  return SPECIES_BY_ID.get(parseRef(ref).id);
}

export function displayName(ref: string): string {
  const { id, shadow } = parseRef(ref);
  const s = SPECIES_BY_ID.get(id);
  if (!s) return ref;
  return shadow ? `${s.name} (Shadow)` : s.name;
}

/**
 * Whether two picks are the same species, and so cannot share a team.
 *
 * GBL forbids duplicate species and decides "duplicate" by **Pokedex number**,
 * not by form or by ref. That one comparison covers every case at once:
 *
 *   - regional forms — Ninetales and Alolan Ninetales are both #38
 *   - a Pokemon and its Mega — same dex by construction
 *   - a Pokemon and its Shadow — a Shadow shares its base form's dex entirely
 *   - alternate forms generally — Origin Dialga, Crowned Zacian, Unown letters
 *
 * Comparing ids would miss all but the last, because every one of those forms
 * carries a distinct id. This is why the check lives here rather than being
 * open-coded as `a !== b` at each call site, which is what it used to be.
 */
export function conflictsOnTeam(a: string, b: string): boolean {
  const sa = speciesOf(a);
  const sb = speciesOf(b);
  return !!sa && !!sb && sa.dex === sb.dex;
}

/** Whether a whole team is free of duplicate species. */
export function teamIsLegal(refs: readonly string[]): boolean {
  for (let i = 0; i < refs.length; i++)
    for (let j = i + 1; j < refs.length; j++)
      if (conflictsOnTeam(refs[i], refs[j])) return false;
  return true;
}

/**
 * Species held out of the simulator because it cannot model them correctly.
 *
 * Each has a mechanic with no representation in the engine: Mimikyu's built-in
 * shield, Morpeko's form change, Aegislash's stance change. None is a stat
 * adjustment — each needs its own code path — and until that exists any number
 * produced for them is confidently wrong, which is worse than absent. Mimikyu
 * in particular ranks 1st in both Great and Ultra, so it led every board.
 *
 * Held out rather than deleted: the data stays complete in species.json, and
 * only selection and the opponent pool skip them. The 2026 engine rewrite is
 * the natural point to revisit this, once the world championship has run on the
 * current system.
 *
 * TO RESTORE: empty this set. Nothing else needs changing — every picker and
 * pool derives from it.
 */
export const UNSIMULATED_IDS: ReadonlySet<string> = new Set([
  'mimikyu',
  'morpeko_full_belly',
  'aegislash_shield',
]);

/** False for a ref whose species the engine cannot model. Shadow-aware. */
export function isSimulated(ref: string): boolean {
  return !UNSIMULATED_IDS.has(parseRef(ref).id);
}

/**
 * Every selectable entry, base forms plus a Shadow row for each eligible
 * form. Used by the battle screen's search, where the two sides are picked
 * independently and a Shadow is a genuinely different opponent.
 *
 * The report screen deliberately does NOT use this - it searches base forms
 * and exposes Shadow as a toggle, so the list stays ~1100 rather than ~1650.
 */
export interface RosterEntry {
  ref: string;
  species: Species;
  shadow: boolean;
  name: string;
}

export const ROSTER: RosterEntry[] = SPECIES.filter((s) => isSimulated(s.id)).flatMap((s) => {
  const base: RosterEntry = { ref: s.id, species: s, shadow: false, name: s.name };
  return s.shadowEligible
    ? [base, { ref: makeRef(s.id, true), species: s, shadow: true, name: `${s.name} (Shadow)` }]
    : [base];
});

export const BASE_ROSTER: RosterEntry[] = ROSTER.filter((r) => !r.shadow);

/**
 * Forms that exist only in Pokemon GO, which the primary source has no artwork
 * for at all.
 *
 * Armored Mewtwo is the case that matters: pokemondb 404s on the slug, so it
 * fell through to the dex-numbered fallback and rendered as *ordinary* Mewtwo,
 * upscaled and pixelated. It read as a dated sprite; it was the wrong species.
 * These come from the mined game assets, so they are the same renders the game
 * itself uses.
 */
const GO_ONLY_SPRITES: Record<string, string> = {
  'mewtwo-armored':
    'https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon/Addressable%20Assets/pm150.fA.icon.png',
};

/**
 * Sprite URL. Form-aware: keyed off the generated slug, not the dex number.
 *
 * The old implementation took only `dex`, so Alolan and Kantonian Marowak
 * (both dex 105) resolved to the same image - every regional variant rendered
 * as its base form.
 *
 * Shadows deliberately reuse the base sprite; in-game they differ only by an
 * aura, which the UI conveys with a badge instead.
 */
export function spriteUrl(sprite: string): string {
  return GO_ONLY_SPRITES[sprite] ?? `https://img.pokemondb.net/sprites/home/normal/${sprite}.png`;
}

/** Fallback when a slug has no artwork - the pre-existing dex-numbered source. */
export function spriteFallbackUrl(dex: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${dex}.png`;
}

/**
 * A random pair to open the battle screen on, drawn from the league's own pool.
 *
 * The screen used to start on the same fixed pair every time, which made it
 * feel like a saved state rather than a sandbox. Drawn from `opponentsFor`
 * rather than the whole roster: that is already the simulated, league-relevant
 * set, so a random pick is a matchup worth looking at instead of two Pokemon
 * nobody brings.
 *
 * Falls back to the first two if a pool is somehow too small to pick from,
 * because a battle screen with one side empty is worse than a dull matchup.
 */
export function randomMatchup(league: LeagueId): [string, string] {
  const pool = opponentsFor(league);
  if (pool.length < 2) return [pool[0]?.id ?? 'azumarill', pool[1]?.id ?? 'lickilicky'];
  const a = Math.floor(Math.random() * pool.length);
  let b = Math.floor(Math.random() * (pool.length - 1));
  // Shift past `a` rather than re-rolling, so the two are never the same and
  // the draw stays uniform over the remaining choices.
  if (b >= a) b += 1;
  return [pool[a].id, pool[b].id];
}

export function opponentsFor(league: LeagueId): Species[] {
  return OPPONENTS[league].filter(isSimulated).map((id) => SPECIES_BY_ID.get(id)!).filter(Boolean);
}

/**
 * Refs worth scanning for breakpoint/bulkpoint relevance in a league - the
 * membership baked in by the generator.
 *
 * Returns *refs*, not Species, because Shadows belong in the scan: ×6/5 attack
 * and ×5/6 defense move a Shadow's thresholds off its base form's, so "does my
 * roll beat Altaria" and "does it beat Shadow Altaria" are different questions
 * and both deserve a cell. A league can rate one form and not the other -
 * Shadow Palkia is Great-ranked where plain Palkia is not.
 */
/**
 * Everything a player may actually bring to a league.
 *
 * Deliberately much wider than `opponentCandidatesFor`. League membership in
 * this codebase means "PvPoke publishes a ranking for it", which is a statement
 * about *relevance*, not legality — GBL lets you bring anything inside the CP
 * cap. Using the ranked set as a picker silently made Altaria unselectable in
 * Great (PvPoke's own #4) and Carbink unselectable in Ultra, and using the top
 * 100 was narrower still.
 *
 * The one real exclusion is Megas and Primals, which GBL does not permit at
 * all, plus the species the engine cannot model. Everything else is offered,
 * ranked or not: an unranked pick simply has no reference column, and the
 * simulation prices it exactly as it prices anything else.
 */
export function pickableFor(_league: LeagueId): string[] {
  return SPECIES.filter((s) => isSimulated(s.id) && !/_mega|_primal/.test(s.id)).flatMap((s) => [
    s.id,
    ...(s.shadowEligible ? [makeRef(s.id, true)] : []),
  ]);
}

export function opponentCandidatesFor(league: LeagueId): string[] {
  return SPECIES.filter((s) => isSimulated(s.id)).flatMap((s) => [
    ...(s.leagues.includes(league) ? [s.id] : []),
    ...(s.shadowLeagues.includes(league) ? [makeRef(s.id, true)] : []),
  ]);
}

/** Ranking of a ref within a league, Shadow-aware. Absent → sorts last. */
export function rankOfRef(ref: string, league: LeagueId): number {
  const { id, shadow } = parseRef(ref);
  const s = SPECIES_BY_ID.get(id);
  const rank = shadow ? s?.shadowLeagueRank[league] : s?.leagueRank[league];
  return rank ?? Number.MAX_SAFE_INTEGER;
}
