import speciesRaw from '../data/species.json';
import opponentsRaw from '../data/opponents.json';
import type { ChargeMove, FastMove, League, LeagueId, Species, SpeciesRef } from './types';

/**
 * The roster is now the whole released game — every species and alternate
 * form (~1123 entries), generated by scripts/build-data.mjs from PvPoke's
 * game master. There is no longer a separate "curated roster" vs "broad
 * opponent pool" split: everything is selectable, and league membership is
 * expressed per-species via `leagues` / `leagueRank`.
 *
 * Shadows are not separate rows. A Shadow shares its base form's stats,
 * typing and movepool exactly, so it's modelled as a flag on the selection
 * (SpeciesRef) rather than a duplicate entry. See SHADOW_ATK_MULT in engine.ts.
 */
/**
 * species.json interns its move objects: the same BODY_SLAM appeared in every
 * species that learns it — 7730 embedded objects across the roster, but only
 * 567 distinct ones, which was 62% of the file. Species now hold keys into a
 * `moves` table.
 *
 * Rehydrating here, once at module load, means the in-memory shape is exactly
 * what it always was and no consumer knows the difference. Shared references
 * are a bonus: identity comparison on moves now works.
 */
interface RawSpecies extends Omit<Species, 'fastMoves' | 'chargeMoves' | 'chargeMove' | 'chargeMove2'> {
  fastMoves: string[];
  chargeMoves: string[];
  chargeMove: string;
  chargeMove2: string | null;
}
const raw = speciesRaw as unknown as {
  moves: Record<string, FastMove & ChargeMove>;
  species: RawSpecies[];
};

export const SPECIES: Species[] = raw.species.map((s) => ({
  ...s,
  fastMoves: s.fastMoves.map((k) => raw.moves[k] as FastMove),
  chargeMoves: s.chargeMoves.map((k) => raw.moves[k] as ChargeMove),
  chargeMove: raw.moves[s.chargeMove] as ChargeMove,
  chargeMove2: s.chargeMove2 ? (raw.moves[s.chargeMove2] as ChargeMove) : null,
}));

export const SPECIES_BY_ID: Map<string, Species> = new Map(SPECIES.map((s) => [s.id, s]));

/** Retained name: the pool and the roster are now the same thing. */
export const OPPONENT_POOL_BY_ID = SPECIES_BY_ID;

export const OPPONENTS: Record<LeagueId, string[]> = opponentsRaw as Record<LeagueId, string[]>;

export const LEAGUES: League[] = [
  { id: 'great', label: 'Great 1500', name: 'Great League · 1500', cap: 1500, uncapped: false },
  { id: 'ultra', label: 'Ultra 2500', name: 'Ultra League · 2500', cap: 2500, uncapped: false },
  { id: 'master', label: 'Master', name: 'Master League · no cap', cap: 1e9, uncapped: true },
];

export const LEAGUE_BY_ID: Map<LeagueId, League> = new Map(LEAGUES.map((l) => [l.id, l]));

const SHADOW_SUFFIX = '_shadow';

/** `machamp_shadow` → `{ id: 'machamp', shadow: true }` */
export function parseRef(ref: string): SpeciesRef {
  return ref.endsWith(SHADOW_SUFFIX)
    ? { id: ref.slice(0, -SHADOW_SUFFIX.length), shadow: true }
    : { id: ref, shadow: false };
}

/** `{ id: 'machamp', shadow: true }` → `machamp_shadow` */
export function makeRef(id: string, shadow: boolean): string {
  return shadow ? `${id}${SHADOW_SUFFIX}` : id;
}

export function speciesOf(ref: string): Species | undefined {
  return SPECIES_BY_ID.get(parseRef(ref).id);
}

export function displayName(ref: string): string {
  const { id, shadow } = parseRef(ref);
  const s = SPECIES_BY_ID.get(id);
  if (!s) return ref;
  return shadow ? `${s.name} (Shadow)` : s.name;
}

/**
 * Every selectable entry, base forms plus a Shadow row for each eligible
 * form. Used by the battle screen's search, where the two sides are picked
 * independently and a Shadow is a genuinely different opponent.
 *
 * The report screen deliberately does NOT use this - it searches base forms
 * and exposes Shadow as a toggle, so the list stays ~1100 rather than ~1650.
 */
export interface RosterEntry {
  ref: string;
  species: Species;
  shadow: boolean;
  name: string;
}

export const ROSTER: RosterEntry[] = SPECIES.flatMap((s) => {
  const base: RosterEntry = { ref: s.id, species: s, shadow: false, name: s.name };
  return s.shadowEligible
    ? [base, { ref: makeRef(s.id, true), species: s, shadow: true, name: `${s.name} (Shadow)` }]
    : [base];
});

export const BASE_ROSTER: RosterEntry[] = ROSTER.filter((r) => !r.shadow);

/**
 * Sprite URL. Form-aware: keyed off the generated slug, not the dex number.
 *
 * The old implementation took only `dex`, so Alolan and Kantonian Marowak
 * (both dex 105) resolved to the same image - every regional variant rendered
 * as its base form.
 *
 * Shadows deliberately reuse the base sprite; in-game they differ only by an
 * aura, which the UI conveys with a badge instead.
 */
export function spriteUrl(sprite: string): string {
  return `https://img.pokemondb.net/sprites/home/normal/${sprite}.png`;
}

/** Fallback when a slug has no artwork - the pre-existing dex-numbered source. */
export function spriteFallbackUrl(dex: number): string {
  return `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${dex}.png`;
}

export function opponentsFor(league: LeagueId): Species[] {
  return OPPONENTS[league].map((id) => SPECIES_BY_ID.get(id)!).filter(Boolean);
}

/**
 * Species worth scanning for breakpoint/bulkpoint relevance in a league -
 * anything ranked inside the cutoff baked in by the generator.
 */
export function opponentCandidatesFor(league: LeagueId): Species[] {
  return SPECIES.filter((s) => s.leagues.includes(league));
}
