import { useMemo, useState } from 'react';
import { ScreenHeader } from '../components/ScreenHeader';
import { ClauseEditor } from '../components/ClauseEditor';
import { FormatSet } from '../components/FormatSet';
import { PoolPreview } from '../components/PoolPreview';
import { TypeFilterRow } from '../components/TypeFilterRow';
import { LEAGUES } from '../lib/data';
import type { LeagueId } from '../lib/types';
import { RULES_SCHEMA, lintFormat, type Format } from '../rules';
import { useFormats, type FormatsApi } from '../state/useFormats';

// New formats start with nothing legal: the type chips and the species picker
// build the pool up from empty, rather than the author's first move always
// being to carve exceptions out of the whole league.
const EMPTY: Format = {
  schema: RULES_SCHEMA,
  base: 'great',
  start: 'empty',
  pool: [],
  composition: { size: 3, uniqueSpecies: true },
  selection: { mode: 'open' },
};

type SavedEntry = FormatsApi['formats'][number];

/**
 * Author a format, and watch the pool move as you do.
 *
 * Saving is blocked while any error diagnostic stands, and only errors block:
 * a narrow pool is a legitimate thing to want and warning about it is the most
 * the tool should do. An unsatisfiable one is not, and shipping it means
 * somebody queues into a format no legal team can enter.
 *
 * Storage is `useFormats()`: localStorage for a signed-out visitor, the
 * server for a signed-in one, migrated automatically the first time a
 * local-format author signs in — see `state/useFormats.ts`. That makes Save
 * asynchronous where it used to be synchronous, so it is additionally
 * disabled while a fetch or migration is in flight, and a failure surfaces as
 * text on the screen rather than an unhandled rejection.
 */
export function FormatBuilderScreen() {
  const { formats: saved, loading, migrating, error, save, remove } = useFormats();
  const [format, setFormat] = useState<Format>(EMPTY);
  const [name, setName] = useState('');
  const [editing, setEditing] = useState<string | undefined>(undefined);
  const [explain, setExplain] = useState('');
  // The raw clause list is generated by the controls above it now, not the
  // primary way in — collapsed by default so it reads as the advanced view.
  const [advancedOpen, setAdvancedOpen] = useState(false);

  const diagnostics = useMemo(() => lintFormat(format), [format]);
  const blocked = diagnostics.some((d) => d.level === 'error') || name.trim() === '' || loading || migrating;

  const onSave = () => {
    if (blocked) return;
    // Capture the saved id and start editing it, so a second Save without
    // reloading updates this same entry instead of minting a duplicate — the
    // same behaviour the pre-hook synchronous version had via saveFormat's
    // return value. A failed save resolves with the id unchanged (or '' for
    // a brand-new one that never got an id), which the falsy check below
    // correctly ignores rather than clobbering `editing` with a bad value.
    void save(name.trim(), format, editing).then((savedId) => {
      if (savedId) setEditing(savedId);
    });
  };

  const onLoad = (s: SavedEntry) => {
    setFormat(s.format);
    setName(s.name);
    setEditing(s.id);
  };

  const onNew = () => {
    setFormat(EMPTY);
    setName('');
    setEditing(undefined);
  };

  // `remove` now issues `deleteServerFormat` for a signed-in author, which
  // cascades the format's entire version history irrecoverably — a bigger
  // blast radius than the localStorage version this screen carried the
  // unconfirmed click over from. The team builder's delete on this same
  // branch confirms; this brings the two into agreement.
  const onDelete = (s: SavedEntry) => {
    if (!window.confirm(`Delete "${s.name}"? This cannot be undone.`)) return;
    void remove(s.id);
  };

  return (
    <>
      <ScreenHeader
        title="Formats"
        blurb="Compose a ruleset clause by clause, and watch the legal pool move with every keystroke."
      />

      {error && (
        <p className="account-alert format-builder-alert" role="alert">
          {error}
        </p>
      )}

      <div className="format-builder">
        <header className="format-builder-head">
          <label className="hud-label" htmlFor="format-name">Format name</label>
          <input
            id="format-name"
            className="input"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Air Ban"
          />

          <label className="hud-label" htmlFor="format-league">League</label>
          <select
            id="format-league"
            value={format.base}
            onChange={(e) => setFormat({ ...format, base: e.target.value as LeagueId })}
          >
            {LEAGUES.map((l) => (
              <option key={l.id} value={l.id}>{l.label}</option>
            ))}
          </select>

          <label className="hud-label" htmlFor="format-size">Team size</label>
          <input
            id="format-size"
            className="input"
            type="number"
            min={1}
            max={6}
            value={format.composition.size}
            onChange={(e) =>
              setFormat({
                ...format,
                composition: { ...format.composition, size: Number(e.target.value) || 1 },
              })
            }
          />

          <button type="button" className="btn chip-btn" onClick={onSave} disabled={blocked}>
            Save
          </button>
          <button type="button" className="btn chip-btn" onClick={onNew}>
            New format
          </button>
        </header>

        <TypeFilterRow format={format} onChange={setFormat} />
        <FormatSet format={format} onChange={setFormat} />

        <div className="format-builder-body">
          <div className="format-builder-advanced">
            <button
              type="button"
              className="btn chip-btn"
              aria-expanded={advancedOpen}
              onClick={() => setAdvancedOpen((v) => !v)}
            >
              {advancedOpen ? 'Hide' : 'Show'} advanced: raw rule list
            </button>
            {advancedOpen && (
              <ClauseEditor
                clauses={format.pool}
                onChange={(pool) => setFormat({ ...format, pool })}
              />
            )}
          </div>

          <div className="format-builder-side">
            <label className="hud-label" htmlFor="explain-ref">Why is this banned?</label>
            <input
              id="explain-ref"
              className="input"
              value={explain}
              onChange={(e) => setExplain(e.target.value)}
              placeholder="azumarill"
            />
            <PoolPreview format={format} explain={explain.trim() || undefined} />
          </div>
        </div>

        <section className="format-saved">
          <p className="hud-label">Saved formats</p>
          <ul>
            {saved.map((s) => (
              <li key={s.id}>
                <button type="button" className="btn chip-btn" onClick={() => onLoad(s)}>
                  Load {s.name}
                </button>
                <button
                  type="button"
                  className="btn chip-btn"
                  onClick={() => onDelete(s)}
                >
                  Delete {s.name}
                </button>
              </li>
            ))}
          </ul>
        </section>
      </div>
    </>
  );
}
