/**
 * Bake the type themes into CSS, and refuse to emit one that fails 508.
 *
 * Hand-picking 64 hex values per theme and eyeballing the result is how you
 * ship a palette that looks fine to whoever chose it and is unreadable to
 * someone else. Each theme here is five colours; the ramps are derived and
 * every pairing the UI renders is measured before anything is written. A
 * theme that misses its target is a build failure, not a judgement call.
 *
 * The derivation lives in src/lib/palette.ts, shared with the custom-theme
 * editor — the same code decides whether a shipped palette and a user's own
 * palette are readable, so the two cannot disagree.
 *
 * Run with `npm run themes`. Output goes to src/styles/types-themes.css.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildPalette, type ThemeBase } from '../src/lib/palette';

// Anchored to the working directory, not to this file: esbuild bundles it into
// node_modules/.cache, so `import.meta.url` points somewhere else entirely.
// npm scripts always run from the package root.
const OUT = join(process.cwd(), 'src/styles/types-themes.css');

const THEMES: (ThemeBase & { id: string; label: string; blurb: string })[] = [
  {
    id: 'water', label: 'Water', scheme: 'dark',
    blurb: 'Deep ocean, cyan signal',
    bg: '#04121e', surface: '#0a2033', text: '#d6e4ee', accent: '#3f9fe0', accent2: '#49d3c4',
  },
  {
    id: 'grass', label: 'Grass', scheme: 'dark',
    blurb: 'Canopy green, citrus signal',
    bg: '#071409', surface: '#0e2413', text: '#dcead9', accent: '#5cb85c', accent2: '#c3e34a',
  },
  {
    id: 'psychic', label: 'Psychic', scheme: 'dark',
    blurb: 'Plum dusk, magenta signal',
    bg: '#150a1c', surface: '#241031', text: '#ebdcf2', accent: '#e0609a', accent2: '#7ad4f0',
  },
  {
    id: 'electric', label: 'Electric', scheme: 'dark',
    blurb: 'Charcoal, high-voltage signal',
    bg: '#101008', surface: '#1c1b0e', text: '#efeada', accent: '#e8c020', accent2: '#63c8f0',
  },
  {
    id: 'fire', label: 'Fire', scheme: 'dark',
    blurb: 'Forge dark, ember signal',
    bg: '#180a06', surface: '#2a120a', text: '#f2e0d6', accent: '#f07030', accent2: '#ffc24a',
  },
  {
    id: 'steel', label: 'Steel', scheme: 'light',
    blurb: 'Brushed metal, cool ink',
    bg: '#eef1f4', surface: '#ffffff', text: '#161b21', accent: '#3c6d92', accent2: '#8a6d3f',
  },
  {
    id: 'ice', label: 'Ice', scheme: 'light',
    blurb: 'Glacier white, frost signal',
    bg: '#f0f6f9', surface: '#ffffff', text: '#10222b', accent: '#1f7f9e', accent2: '#6a52b5',
  },
];

const failures: string[] = [];
let css = `/* \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550
   TYPE THEMES \u2014 generated by scripts/build-themes.ts. Do not hand-edit.

   Each theme is derived from five colours and then checked: body text clears
   4.5:1 against both its grounds, the accents clear 4.5:1 where they carry
   text, and the faint tier clears 3:1. The generator refuses to emit a theme
   that misses, so a palette cannot regress into being unreadable.
   \u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550 */
`;

for (const t of THEMES) {
  const { tokens, checks } = buildPalette(t);
  for (const c of checks) {
    console.log(`${t.id.padEnd(9)} ${c.name.padEnd(28)} ${c.ratio.toFixed(2)}:1  (needs ${c.needs})`);
    if (!c.ok) failures.push(`${t.id}: ${c.name} is ${c.ratio.toFixed(2)}:1, needs ${c.needs}`);
  }
  const body = Object.entries(tokens)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  css += `
:root[data-theme='${t.id}'],
/* The preview tile carries this attribute, so it renders in this theme's own
   tokens and cannot drift from the real palette. Deliberately the tile and not
   the button around it: on the button it also recoloured the label, which made
   every light theme's name unreadable against a dark panel. */
.theme-swatch-face[data-theme='${t.id}'] {
${body}
}
`;
}

if (failures.length) {
  console.error('\nCONTRAST FAILURES:\n' + failures.map((f) => '  ' + f).join('\n'));
  process.exit(1);
}

writeFileSync(OUT, css);
console.log(`\nwrote ${OUT} \u2014 ${THEMES.length} themes, every pairing clears its target`);
